// src/components/SearchPage.vue
<template>
  <Layout>
    <header>
      <div class="container">
        <h1>Inbox Graph</h1>
        <div>
          <span id="auth-status" class="auth-status">Checking...</span>
          <a href="/auth/google" class="btn btn-primary" style="margin-left: 12px">
            <Mail :size="14" style="margin-right: 4px; vertical-align: middle" />
            Login with Gmail
          </a>
        </div>
      </div>
    </header>
    <div class="container">
      <div class="search-bar">
        <div class="search-input-wrapper">
          <Search :size="18" class="search-icon" />
          <input type="text" id="search-input" class="search-input" placeholder="Search emails or enter an email address..." autofocus />
        </div>
      </div>
      <div id="results" />
      <div id="thread-view" class="hidden" />
    </div>
    <ClientScript />
  </Layout>
</template>

<script setup lang="ts">
import Layout from './Layout.vue'
import ClientScript from './ClientScript.vue'
import { Mail, Search } from '@lucide/vue'
</script>

// src/components/SearchPage.tsx
import { ClientScript } from './ClientScript.js'
import { Layout } from './Layout.js'

export function SearchPage() {
  return (
    <Layout>
      <header>
        <div className="container">
          <h1>Inbox Graph</h1>
          <div>
            <span id="auth-status" className="auth-status">
              Checking...
            </span>
            <a href="/auth/google" className="btn btn-primary" style={{ marginLeft: '12px' }}>
              Login with Gmail
            </a>
          </div>
        </div>
      </header>
      <div className="container">
        <div className="search-bar">
          <input
            type="text"
            id="search-input"
            className="search-input"
            placeholder="Search emails or enter an email address..."
            autoFocus={true}
          />
        </div>
        <div id="results" />
        <div id="thread-view" className="hidden" />
      </div>
      <ClientScript />
    </Layout>
  )
}
