// src/components/ResultsList.tsx
import { MessageCard, type MessageData } from './MessageCard.js'
import { PersonCard } from './PersonCard.js'

interface ResultsListProps {
  messages: MessageData[]
  person?: { name: string; email: string; _key: string }
  stats?: { sent: number; received: number; threads: number }
}

export function ResultsList({ messages, person, stats }: ResultsListProps) {
  if (messages.length === 0) {
    return <div className="empty">No results found</div>
  }
  return (
    <>
      {person && stats ? <PersonCard data={{ person, stats }} /> : null}
      {messages.map((m) => (
        <MessageCard key={m._key} message={m} />
      ))}
    </>
  )
}

// packages/client/src/components/ResultsList.vue
<template>
  <div v-if="!messages.length" class="empty">No results found</div>
  <template v-else>
    <PersonCard v-if="person && stats" :data="{ person, stats }" />
    <MessageCard v-for="m in messages" :key="m._key" :message="m" @click="emit('select-thread', m.threadId)" />
  </template>
</template>

<script setup lang="ts">
import type { MessageData } from './MessageCard.vue'
import MessageCard from './MessageCard.vue'
import PersonCard from './PersonCard.vue'

defineProps<{
  messages: MessageData[]
  person?: { name: string; email: string; _key: string } | null
  stats?: { sent: number; received: number; threads: number } | null
}>()

const emit = defineEmits<{
  'select-thread': [threadId: string]
}>()
</script>
